version: '3.4'

services:
  catalogdb:
    image: mongo
    networks:
      - catalog_net
  
  catalog.api:
    image: ${DOCKER_REGISTRY-}catalogapi
    networks:
      - catalog_net
    build:
      context: .
      dockerfile: Services/Catalog/Catalog.API/Dockerfile



networks:
  catalog_net:
    driver: bridge

volumes:
  mongo_data:    